version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.14.10

commands:
  init_and_validate:
    steps:
      - run:
          name: terraform validate
          command: |
            cd ./src/tf
            terraform init -backend=false
            terraform validate
  init_and_plan:
    steps:
      - run:
          name: terraform plan
          command: |
            cd ./src/tf
            terraform init -input=false
            terraform plan

jobs:
  validate:
    executor: 
      name: default
    steps:
      - checkout
      - init_and_validate
  plan:
    executor: 
      name: default
    steps:
      - checkout
      - init_and_plan

workflows:
  version: 2
  push:
    jobs:
      - validate
      - plan:
          requires:
            - validate
