version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.14.10

commands:
  install_awscli:
    steps:
      - run:
          name: install_awscli
          command: |
            apk add sudo jq 
            apk --update-cache add python3 py3-pip alpine-sdk
            sudo pip3 install awscli --upgrade
            sudo aws --version
  init_and_validate:
    steps:
      - run:
          name: terraform validate
          command: |
            cd ./src/tf
            terraform init -backend=false
            terraform validate
  init_and_plan:
    steps:
      - run:
          name: terraform plan
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform init -input=false
            terraform plan

jobs:
  validate:
    executor: 
      name: default
    steps:
      - checkout
      - init_and_validate
  plan:
    executor: 
      name: default
    steps:
      - checkout
      - install_awscli
      - init_and_plan

workflows:
  version: 2
  push:
    jobs:
      - validate
      - plan:
          requires:
            - validate
          context: TERRAFORM-CI-DEMO
