version: 2.1

orbs:
  slack: circleci/slack@4.5.0

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.14.10

commands:
  install_awscli:
    steps:
      - run:
          name: install awscli
          command: |
            apk add sudo jq 
            apk --update-cache add python3 py3-pip alpine-sdk
            sudo pip3 install awscli --upgrade
            sudo aws --version
  validate:
    steps:
      - run:
          name: terraform validate
          command: |
            cd ./src/tf
            terraform init -backend=false
            terraform validate
  int_and_plan:
    steps:
      - run:
          name: terraform plan
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform init -input=false
            rm -f plan.out
            terraform plan -out=plan.out
  apply:
    steps:
      - run:
          name: terraform apply
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform apply -auto-approve plan.out

jobs:
  checkout_code:
    executor: 
      name: default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  validate:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - validate
  int_and_plan:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - install_awscli
      - int_and_plan
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - install_awscli
      - apply
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - validate:
          requires:
            - checkout_code
      - int_and_plan:
          requires:
            - validate
          context:
            - TERRAFORM-CI-DEMO
            - SLACK_INTEGRATION
      - slack/on-hold:
          context: SLACK_INTEGRATION
          requires:
            - int_and_plan
          filters:
            branches:
              ignore:
                - /.*/
      - hold_apply:
          requires:
            - int_and_plan
            - slack/on-hold
          type: approval
          filters:
            branches:
              only:
                - "main"
      - apply:
          requires:
            - hold_apply
          context:
            - TERRAFORM-CI-DEMO
            - SLACK_INTEGRATION
          filters:
            branches:
              only:
                - "main"
