version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:0.14.10

commands:
  install_awscli:
    steps:
      - run:
          name: install_awscli
          command: |
            apk add sudo jq 
            apk --update-cache add python3 py3-pip alpine-sdk
            sudo pip3 install awscli --upgrade
            sudo aws --version
  init:
    steps:
      - run:
          name: terraform init
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform init -input=false
  validate:
    steps:
      - run:
          name: terraform validate
          command: |
            cd ./src/tf
            terraform validate
  plan:
    steps:
      - run:
          name: terraform plan
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform plan
  apply:
    steps:
      - run:
          name: terraform apply
          command: |
            sh ./bin/assume-role.sh
            source aws-env.sh
            cd ./src/tf
            terraform apply -auto-approve

jobs:
  checkout:
    executor: 
      name: default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  init:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - install_awscli
      - init
      - persist_to_workspace:
          root: .
          paths:
            - .
  validate:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - validate
  plan:
    executor: 
      name: default
    steps:
      - attach_workspace:
          at: .
      - install_awscli
      - plan

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - init:
          requires:
            - checkout
      - validate:
          requires:
            - init
      - plan:
          requires:
            - validate
          context: TERRAFORM-CI-DEMO
